const PASS="Yusuf";
const STORE="tytAnalizProV2";
const today=()=>new Date().toISOString().slice(0,10);
const subjects={
  turkce:{name:"Türkçe",max:40,topics:["Paragraf","Dil Bilgisi","Sözcükte Anlam","Cümlede Anlam","Yazım-Noktalama","Ses Bilgisi"]},
  matematik:{name:"Matematik",max:40,topics:["Problemler","Temel Kavramlar","Sayılar","Fonksiyon","Denklem-Eşitsizlik","Geometri"]},
  sosyal:{name:"Sosyal",max:20,topics:["Tarih","Coğrafya","Felsefe","Din Kültürü"]},
  fen:{name:"Fen",max:20,topics:["Fizik","Kimya","Biyoloji"]}
};
const branchDefs={
  turkce:{name:"Türkçe Branş",max:40,topics:subjects.turkce.topics},
  matematik:{name:"Matematik Branş",max:30,topics:["Problemler","Temel Kavramlar","Sayılar","Fonksiyon","Denklem-Eşitsizlik","Veri-Olasılık"]},
  geometri:{name:"Geometri Branş",max:10,topics:["Üçgenler","Dörtgenler","Çember-Daire","Analitik Geometri","Katı Cisimler"]},
  fizik:{name:"Fizik Branş",max:7,topics:["Fizik Bilimine Giriş","Madde ve Özellikleri","Hareket-Kuvvet","Enerji","Optik","Dalgalar","Elektrik"]},
  kimya:{name:"Kimya Branş",max:7,topics:["Kimya Bilimi","Atom-Periyodik","Kimyasal Türler","Maddenin Halleri","Karışımlar","Asit-Baz-Tuz"]},
  biyoloji:{name:"Biyoloji Branş",max:6,topics:["Canlıların Ortak Özellikleri","Hücre","Canlıların Sınıflandırılması","Kalıtım","Ekoloji"]},
  tarih:{name:"Tarih Branş",max:5,topics:["İlk Çağ","İslam Tarihi","Türk-İslam","Osmanlı","Milli Mücadele"]},
  cografya:{name:"Coğrafya Branş",max:5,topics:["Doğa-İnsan","Harita","İklim","Nüfus","Türkiye Coğrafyası"]},
  felsefe:{name:"Felsefe Branş",max:5,topics:["Felsefeye Giriş","Bilgi","Varlık","Ahlak","Din-Siyaset-Bilim"]},
  din:{name:"Din Kültürü Branş",max:5,topics:["Bilgi-İnanç","İbadet","Ahlak","Hz. Muhammed","İslam Düşüncesi"]}
};
const reasons=["Konu eksik","Dikkat hatası","Zaman yetmedi","Boş bıraktım","Şıklar arasında kaldım","Yarım biliyorum"];
let db=JSON.parse(localStorage.getItem(STORE)||'{"exams":[]}');
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(STORE,JSON.stringify(db));renderAll();}
function net(d,y){return +(d-y/4).toFixed(2)}
function totalNet(exam){return Object.values(exam.subjects||{}).reduce((a,s)=>a+net(s.d,s.y),0)}
function q(sel){return document.querySelector(sel)}
function clamp(v,min,max){v=Number(v)||0;return Math.max(min,Math.min(max,v))}

$('loginBtn').onclick=()=>{if($('passwordInput').value===PASS){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');renderAll()}else alert('Şifre yanlış.');};
$('passwordInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));$(b.dataset.page).classList.add('active-page');renderAll();});

function makeCounter(id,label,max,onChange){return `<div class="counter"><label>${label}<b id="${id}Val">0</b></label><div class="stepper"><button data-step="${id}" data-delta="-1">−</button><input id="${id}" type="number" min="0" max="${max}" value="0"><button data-step="${id}" data-delta="1">+</button></div><input id="${id}Range" type="range" min="0" max="${max}" value="0"></div>`}
function bindCounter(id,max,cb){const n=$(id),r=$(id+'Range'),v=$(id+'Val');function sync(x){x=clamp(x,0,max);n.value=x;r.value=x;v.textContent=x;cb&&cb()}n.oninput=()=>sync(n.value);r.oninput=()=>sync(r.value);document.querySelectorAll(`[data-step="${id}"]`).forEach(b=>b.onclick=()=>sync(+n.value + +b.dataset.delta));sync(0)}
function renderSubjectInputs(){const box=$('tytInputs');box.innerHTML='';Object.entries(subjects).forEach(([key,s])=>{box.insertAdjacentHTML('beforeend',`<div class="subject-box" data-sub="${key}"><div class="subject-title"><h3>${s.name} <small>/${s.max}</small></h3><span class="net-pill" id="${key}Net">0 net</span></div><div class="counter-grid">${makeCounter(key+'D','Doğru',s.max)}${makeCounter(key+'Y','Yanlış',s.max)}${makeCounter(key+'B','Boş',s.max)}</div><div class="topic-grid">${s.topics.map(t=>`<div class="topic-card"><b>${t}</b><small> Yanlış sayısı ve sebep</small><div class="stepper"><button data-topic="${key}|${t}" data-delta="-1">−</button><input data-topic-input="${key}|${t}" type="number" min="0" value="0"><button data-topic="${key}|${t}" data-delta="1">+</button></div><div class="reason-selects"><select data-reason="${key}|${t}">${reasons.map(r=>`<option>${r}</option>`).join('')}</select></div></div>`).join('')}</div></div>`)});Object.entries(subjects).forEach(([key,s])=>['D','Y','B'].forEach(k=>bindCounter(key+k,s.max,validateTyt)));document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{const inp=document.querySelector(`[data-topic-input="${b.dataset.topic}"]`);inp.value=clamp(+inp.value + +b.dataset.delta,0,99)});}
function validateTyt(){let total=0,msg=[];Object.entries(subjects).forEach(([key,s])=>{let d=clamp($(key+'D').value,0,s.max),y=clamp($(key+'Y').value,0,s.max),b=clamp($(key+'B').value,0,s.max);if(d+y+b>s.max){msg.push(`${s.name}: doğru + yanlış + boş ${s.max} soruyu geçemez.`)}total+=d+y+b;$(key+'Net').textContent=net(d,y)+' net';});if(total>120)msg.push('TYT toplamı 120 soruyu geçemez.');$('validationBox').textContent=msg.length?msg.join(' '):`Kontrol başarılı. Girilen toplam soru: ${total}/120`;return !msg.length}
function collectTyt(){if(!validateTyt())return null;let ex={id:crypto.randomUUID(),type:'tyt',name:$('examName').value||'TYT Denemesi',date:$('examDate').value||today(),subjects:{},topics:[]};Object.entries(subjects).forEach(([key,s])=>{let d=+$(key+'D').value,y=+$(key+'Y').value,b=+$(key+'B').value;ex.subjects[key]={name:s.name,max:s.max,d,y,b};s.topics.forEach(t=>{let wrong=+document.querySelector(`[data-topic-input="${key}|${t}"]`).value||0;let reason=document.querySelector(`[data-reason="${key}|${t}"]`).value;if(wrong>0)ex.topics.push({subject:s.name,topic:t,wrong,reason});});});return ex}
$('saveTytBtn').onclick=()=>{const ex=collectTyt();if(ex){db.exams.push(ex);save();alert('TYT denemesi kaydedildi.')}};

function renderBranch(){const sel=$('branchSelect');sel.innerHTML=Object.entries(branchDefs).map(([k,b])=>`<option value="${k}">${b.name} / ${b.max} soru</option>`).join('');sel.onchange=renderBranchInput;renderBranchInput();}
function renderBranchInput(){const k=$('branchSelect').value||'turkce',b=branchDefs[k];$('branchInput').innerHTML=`<div class="subject-box"><div class="subject-title"><h3>${b.name}</h3><span class="net-pill" id="branchNet">0 net</span></div><div class="counter-grid">${makeCounter('brD','Doğru',b.max)}${makeCounter('brY','Yanlış',b.max)}${makeCounter('brB','Boş',b.max)}</div><div class="topic-grid">${b.topics.map(t=>`<div class="topic-card"><b>${t}</b><div class="stepper"><button data-br-topic="${t}" data-delta="-1">−</button><input data-br-input="${t}" type="number" value="0"><button data-br-topic="${t}" data-delta="1">+</button></div><select data-br-reason="${t}">${reasons.map(r=>`<option>${r}</option>`).join('')}</select></div>`).join('')}</div></div>`;['D','Y','B'].forEach(x=>bindCounter('br'+x,b.max,()=>{$('branchNet').textContent=net($('brD').value,$('brY').value)+' net'}));document.querySelectorAll('[data-br-topic]').forEach(btn=>btn.onclick=()=>{const i=document.querySelector(`[data-br-input="${btn.dataset.brTopic}"]`);i.value=clamp(+i.value + +btn.dataset.delta,0,99)});}
$('saveBranchBtn').onclick=()=>{const k=$('branchSelect').value,b=branchDefs[k],d=+$('brD').value,y=+$('brY').value,bo=+$('brB').value;if(d+y+bo>b.max)return alert(`${b.name} toplamı ${b.max} soruyu geçemez.`);let ex={id:crypto.randomUUID(),type:'branch',branch:k,name:$('branchName').value||b.name,date:$('branchDate').value||today(),subjects:{[k]:{name:b.name,max:b.max,d,y,b:bo}},topics:[]};b.topics.forEach(t=>{let wrong=+document.querySelector(`[data-br-input="${t}"]`).value||0;if(wrong>0)ex.topics.push({subject:b.name,topic:t,wrong,reason:document.querySelector(`[data-br-reason="${t}"]`).value})});db.exams.push(ex);save();alert('Branş denemesi kaydedildi.');};

function renderDashboard(){const tyt=db.exams.filter(e=>e.type==='tyt').sort((a,b)=>a.date.localeCompare(b.date));let last=tyt.at(-1);$('lastNet').textContent=last?totalNet(last):0;$('heroTitle').textContent=last?`${last.name}: ${totalNet(last)} net`:'Henüz deneme yok';$('heroText').textContent=last?'Son denemene göre öncelikli konuları aşağıda görebilirsin.':'İlk denemeni gir; sistem otomatik analiz çıkaracak.';let cards=['turkce','matematik','sosyal','fen'].map(k=>{let s=last?.subjects?.[k];return `<div class="mini-card"><span>${subjects[k].name}</span><b>${s?net(s.d,s.y):0}</b><span>${s?`${s.d}D ${s.y}Y ${s.b}B`:''}</span></div>`}).join('');$('summaryCards').innerHTML=cards;drawLine($('netTrend'),tyt.map(e=>e.name),tyt.map(totalNet));drawBar($('reasonChart'),reasonStats());renderPriority();}
function reasonStats(){let map={};db.exams.forEach(e=>(e.topics||[]).forEach(t=>map[t.reason]=(map[t.reason]||0)+t.wrong));return map}
function topicStats(){let map={};db.exams.forEach(e=>(e.topics||[]).forEach(t=>{let key=t.subject+' - '+t.topic;if(!map[key])map[key]={wrong:0,count:0,reasons:{}};map[key].wrong+=t.wrong;map[key].count++;map[key].reasons[t.reason]=(map[key].reasons[t.reason]||0)+t.wrong;}));return map}
function renderPriority(){let rows=Object.entries(topicStats()).map(([k,v])=>{let score=v.wrong*12+v.count*8;let main=Object.entries(v.reasons).sort((a,b)=>b[1]-a[1])[0]?.[0]||'-';return {k,score,main,v}}).sort((a,b)=>b.score-a.score).slice(0,8);$('priorityList').innerHTML=rows.length?rows.map(r=>`<div class="priority-item"><div><b>${r.k}</b><br><small>${r.v.wrong} yanlış, ${r.v.count} denemede tekrar • Ana sebep: ${r.main}</small></div><span class="priority-score">${r.score}</span></div>`).join(''):'Henüz konu hatası girilmedi.';}
function drawLine(c,labels,data){const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1020';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(50,i*h/5);ctx.lineTo(w-20,i*h/5);ctx.stroke()}if(!data.length){ctx.fillStyle='#9dafcf';ctx.font='28px Arial';ctx.fillText('Veri yok',w/2-50,h/2);return}let max=Math.max(120,...data),min=0,pts=data.map((v,i)=>[50+i*((w-90)/Math.max(1,data.length-1)),h-40-((v-min)/(max-min))*(h-80)]);ctx.strokeStyle='#6ee7f9';ctx.lineWidth=5;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.fillStyle='#fff';ctx.font='18px Arial';pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p[0],p[1],7,0,7);ctx.fill();ctx.fillText(data[i],p[0]-10,p[1]-14)});}
function drawBar(c,map){const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1020';ctx.fillRect(0,0,w,h);let entries=Object.entries(map);if(!entries.length){ctx.fillStyle='#9dafcf';ctx.font='28px Arial';ctx.fillText('Veri yok',w/2-50,h/2);return}let max=Math.max(...entries.map(e=>e[1]),1),barW=(w-80)/entries.length;entries.forEach(([k,v],i)=>{let bh=(v/max)*(h-90),x=45+i*barW,y=h-45-bh;let g=ctx.createLinearGradient(0,y,0,h);g.addColorStop(0,'#8b5cf6');g.addColorStop(1,'#6ee7f9');ctx.fillStyle=g;ctx.fillRect(x,y,barW-18,bh);ctx.fillStyle='#fff';ctx.font='16px Arial';ctx.fillText(v,x+8,y-8);ctx.save();ctx.translate(x+8,h-25);ctx.rotate(-.25);ctx.fillStyle='#9dafcf';ctx.fillText(k,0,0);ctx.restore();});}
function renderCompareOptions(){let tyt=db.exams.filter(e=>e.type==='tyt');let opts=tyt.map(e=>`<option value="${e.id}">${e.date} - ${e.name} (${totalNet(e)} net)</option>`).join('');$('compareA').innerHTML=opts;$('compareB').innerHTML=opts;if(tyt.length>1)$('compareB').selectedIndex=tyt.length-1;}
$('compareBtn').onclick=()=>{let a=db.exams.find(e=>e.id===$('compareA').value),b=db.exams.find(e=>e.id===$('compareB').value);if(!a||!b)return;$('compareResult').innerHTML=`<h3>Toplam fark: ${(totalNet(b)-totalNet(a)).toFixed(2)} net</h3>`+Object.keys(subjects).map(k=>{let av=net(a.subjects[k].d,a.subjects[k].y),bv=net(b.subjects[k].d,b.subjects[k].y),diff=(bv-av).toFixed(2);return `<div class="compare-line"><b>${subjects[k].name}</b><span>${av} → ${bv} (${diff>0?'+':''}${diff})</span></div>`}).join('');};
function renderHistory(){$('historyList').innerHTML=db.exams.length?db.exams.slice().reverse().map(e=>`<div class="history-item"><div><b>${e.name}</b><br><small>${e.date} • ${e.type==='tyt'?'TYT':'Branş'} • ${totalNet(e)} net</small></div><button onclick="deleteExam('${e.id}')" class="ghost danger">Sil</button></div>`).join(''):'Kayıtlı deneme yok.';}
window.deleteExam=id=>{if(confirm('Bu deneme silinsin mi?')){db.exams=db.exams.filter(e=>e.id!==id);save();}};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tyt-analiz-yedek.json';a.click();};
$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.exams))throw Error();db=data;save();alert('Analiz dosyası yüklendi.')}catch{alert('Dosya okunamadı.')}};r.readAsText(f);};
$('clearBtn').onclick=()=>{if(confirm('Tüm kayıtlar silinsin mi?')){db={exams:[]};save();}};
$('sampleBtn').onclick=()=>{db.exams=[
{id:crypto.randomUUID(),type:'tyt',name:'TYT Deneme 1',date:'2026-04-10',subjects:{turkce:{name:'Türkçe',max:40,d:25,y:8,b:7},matematik:{name:'Matematik',max:40,d:9,y:0,b:31},sosyal:{name:'Sosyal',max:20,d:15,y:4,b:1},fen:{name:'Fen',max:20,d:14,y:5,b:1}},topics:[{subject:'Türkçe',topic:'Paragraf',wrong:5,reason:'Dikkat hatası'},{subject:'Matematik',topic:'Problemler',wrong:6,reason:'Konu eksik'},{subject:'Fen',topic:'Fizik',wrong:2,reason:'Yarım biliyorum'}]},
{id:crypto.randomUUID(),type:'tyt',name:'TYT Deneme 2',date:'2026-04-20',subjects:{turkce:{name:'Türkçe',max:40,d:28,y:6,b:6},matematik:{name:'Matematik',max:40,d:12,y:2,b:26},sosyal:{name:'Sosyal',max:20,d:16,y:3,b:1},fen:{name:'Fen',max:20,d:13,y:4,b:3}},topics:[{subject:'Türkçe',topic:'Dil Bilgisi',wrong:3,reason:'Konu eksik'},{subject:'Matematik',topic:'Problemler',wrong:5,reason:'Konu eksik'},{subject:'Fen',topic:'Fizik',wrong:3,reason:'Şıklar arasında kaldım'}]}
];save();};
function renderReport(){let tyt=db.exams.filter(e=>e.type==='tyt').sort((a,b)=>a.date.localeCompare(b.date));let last=tyt.at(-1);let priorities=Object.entries(topicStats()).map(([k,v])=>({k,wrong:v.wrong,count:v.count,reason:Object.entries(v.reasons).sort((a,b)=>b[1]-a[1])[0]?.[0]||'-',score:v.wrong*12+v.count*8})).sort((a,b)=>b.score-a.score).slice(0,10);$('printReport').innerHTML=`<div class="report-page"><h1>TYT Deneme Analiz Raporu</h1><p>Tarih: ${today()}</p><div class="report-grid">${Object.keys(subjects).map(k=>{let s=last?.subjects?.[k];return `<div class="report-box"><h3>${subjects[k].name}</h3><b>${s?net(s.d,s.y):0} net</b><p>${s?`${s.d} doğru • ${s.y} yanlış • ${s.b} boş`:''}</p></div>`}).join('')}</div><h2>Net Zaman Grafiği</h2><canvas class="report-chart" id="reportTrend" width="900" height="300"></canvas></div><div class="report-page"><h2>Öncelikli Konular</h2><table class="report-table"><tr><th>Konu</th><th>Yanlış</th><th>Tekrar</th><th>Ana Sebep</th><th>Öncelik</th></tr>${priorities.map(p=>`<tr><td>${p.k}</td><td>${p.wrong}</td><td>${p.count}</td><td>${p.reason}</td><td>${p.score}</td></tr>`).join('')}</table><h2>Çalışma Yorumu</h2><p>${priorities[0]?`İlk öncelik ${priorities[0].k}. Bu konu ${priorities[0].count} farklı kayıtta tekrar etmiş. Ana sebep: ${priorities[0].reason}.`: 'Henüz yeterli konu verisi yok.'}</p></div>`;setTimeout(()=>drawLine($('reportTrend'),tyt.map(e=>e.name),tyt.map(totalNet)),50);}
$('printBtn').onclick=()=>{renderReport();setTimeout(()=>window.print(),150)};
function renderAll(){renderDashboard();renderCompareOptions();renderHistory();renderReport();}
$('examDate').value=today();$('branchDate').value=today();renderSubjectInputs();renderBranch();renderAll();
