const PASS='Yusuf';
const STORE='tytAnalizProV3';
const pages={dashboard:'Genel Bakış',upload:'Dosya Yükle',manual:'Manuel / Düzelt',topics:'Konu Analizi',compare:'Karşılaştır',branch:'Branş Denemesi',history:'Geçmiş & Yedek',report:'A4 Rapor'};
const lessons=[{key:'turkce',name:'Türkçe',max:40},{key:'sosyal',name:'T.Sosyal',max:25},{key:'matematik',name:'T.Matematik',max:40},{key:'fen',name:'T.Fen',max:20}];
const reasons=['Belirtilmedi','Dikkat hatası','Konu eksiği','Yarım biliyorum','Zaman yetmedi','Şıklar arasında kaldım','Boş bıraktım'];
const branchTypes=['Türkçe','Paragraf','Dil Bilgisi','Matematik','Problemler','Geometri','Sosyal','Tarih','Coğrafya','Felsefe','Din Kültürü','Fen','Fizik','Kimya','Biyoloji'];
let db={exams:[],branches:[]}; let draft=null; let charts={};
const $=id=>document.getElementById(id);
function saveDB(){localStorage.setItem(STORE,JSON.stringify(db));}
function loadDB(){try{db=JSON.parse(localStorage.getItem(STORE))||db}catch(e){} if(!db.exams)db.exams=[]; if(!db.branches)db.branches=[];}
function net(d,y){return +(Number(d||0)-Number(y||0)/4).toFixed(2)}
function sumNet(exam){return lessons.reduce((a,l)=>a+net(exam.lessons?.[l.key]?.correct,exam.lessons?.[l.key]?.wrong),0).toFixed(2)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}

document.addEventListener('DOMContentLoaded',()=>{loadDB(); initLogin(); initNav(); buildManual(); initUpload(); initCompare(); initBranch(); initHistory(); renderAll();});
function initLogin(){ if(sessionStorage.getItem('tyt-auth')==='1'){ $('login').classList.add('hidden'); $('app').classList.remove('hidden'); } $('loginBtn').onclick=()=>{ if($('passwordInput').value===PASS){sessionStorage.setItem('tyt-auth','1');$('login').classList.add('hidden');$('app').classList.remove('hidden');renderAll()} else $('loginError').textContent='Şifre hatalı.'}; $('passwordInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()}); $('logoutBtn').onclick=()=>{sessionStorage.removeItem('tyt-auth');location.reload()}; $('printBtn').onclick=()=>{showPage('report');setTimeout(()=>window.print(),250)};}
function initNav(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));}
function showPage(id){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id)); $('pageTitle').textContent=pages[id]; $('pageSubtitle').textContent=id==='upload'?'PDF/TXT/JSON sonucunu yükle, sonra kontrol edip kaydet.':id==='manual'?'Otomatik gelen veriyi düzelt veya sıfırdan gir.':id==='report'?'A4 arkalı önlü yazdırmaya uygun rapor.':'TYT deneme analiz sistemi.'; renderAll();}
function initUpload(){ $('parseBtn').onclick=parseSelectedFile; $('sampleBtn').onclick=()=>{draft=sampleExam(); fillReview(draft); showPage('upload');}; $('saveReviewedBtn').onclick=()=>{if(!draft)return; const edited=readReview(); saveExam(edited); $('reviewPanel').classList.add('hidden'); alert('Deneme kaydedildi.');}; $('sendToManualBtn').onclick=()=>{if(!draft)return; fillManual(draft); showPage('manual')};}
async function parseSelectedFile(){const f=$('fileInput').files[0]; if(!f){$('parseStatus').textContent='Önce dosya seç.';return} $('parseStatus').textContent='Dosya okunuyor...'; try{ if(f.name.toLowerCase().endsWith('.json')){const obj=JSON.parse(await f.text()); if(obj.exams){db=obj;saveDB();renderAll();$('parseStatus').textContent='Yedek yüklendi.';return} draft=normalizeExam(obj.exam||obj); } else {let text=''; if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')) text=await readPdf(f); else text=await f.text(); draft=parseResultText(text); } fillReview(draft); $('parseStatus').textContent='Okundu. Şimdi kontrol edip kaydet.';}catch(e){console.error(e);$('parseStatus').textContent='Okuma sırasında sorun oldu. PDF metni kopyalayıp TXT olarak yükleyebilirsin.'}}
async function readPdf(file){ if(!window.pdfjsLib) throw new Error('pdfjs yok'); pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'; const buf=await file.arrayBuffer(); const pdf=await pdfjsLib.getDocument({data:buf}).promise; let out=''; for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p); const txt=await page.getTextContent(); out+=txt.items.map(i=>i.str).join('\n')+'\n';} return out;}
function cleanText(t){return t.replace(/\r/g,'\n').replace(/[ \t]+/g,' ').replace(/\n{2,}/g,'\n').replace(/MATEMAT\s*İ\s*K/gi,'MATEMATİK').replace(/T\.MATEMAT\s*İ\s*K/gi,'T.MATEMATİK').replace(/T\.SOSYAL/gi,'T.SOSYAL').replace(/T\.FEN/gi,'T.FEN').replace(/İ\s*L/gi,'İL').trim();}
function parseResultText(raw){const t=cleanText(raw); const flat=t.replace(/\n/g,' '); const exam={id:uid(),source:'file',name:pick(flat,/Sınav Adı\s*:\s*(.+?)\s*Sınav Tarihi/i)||'Yüklenen Deneme',date:toISO(pick(flat,/Sınav Tarihi\s*:\s*(\d{2}[-.]\d{2}[-.]\d{4})/i))||today(),score:num(pick(flat,/Puan Türleri.*?TYT\s+([\d.]+)/i))||num(pick(flat,/TYT\s+([\d.]{3,})\s+\d/i)),rank:num(pick(flat,/TYT\s+[\d.]+\s+[\d.]+\s+(\d+)\s+\d+/i)),lessons:{},topics:[],historyFromFile:[]}; lessons.forEach(l=>{const label=l.name.replace('T.','T\\.').replace('İ','[İI]'); const r=new RegExp(label+'\\s+'+l.max+'\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)\\s+([\\d.]+)','i'); const m=flat.match(r); exam.lessons[l.key]=m?{total:l.max,correct:+m[1],wrong:+m[2],blank:+m[3],net:+m[4]}:{total:l.max,correct:0,wrong:0,blank:l.max,net:0};}); exam.topics=parseTopics(t); const histBlock=(t.split(/Sınavlar Arası Karşılaştırma/i)[1]||'').split(/TÜRKÇE\s*\n\s*C/i)[0]||''; histBlock.split('\n').forEach(line=>{const m=line.match(/(\d{2}-\d{2}-\d{4})\s+(.+?)\s+([\d.]+)\s+([\d.]+)\s+(\d+)/); if(m)exam.historyFromFile.push({date:toISO(m[1]),name:m[2].trim(),score:+m[3],net:+m[4],rank:+m[5]});}); return normalizeExam(exam);}
function parseTopics(t){const sections=[['turkce','TÜRKÇE','T.SOSYAL'],['sosyal','T.SOSYAL','T.MATEMATİK'],['matematik','T.MATEMATİK','T.FEN'],['fen','T.FEN','EDEBİYAT']]; const rows=[]; sections.forEach(([key,start,end])=>{let part=t.split(new RegExp(start+'\\s*\\n\\s*C','i'))[1]||''; part=part.split(new RegExp(end+'\\s*\\n\\s*C','i'))[0]||part; const re=/(\d{1,2})_([^\n]+)\n\s*([DYB])/g; let m; while((m=re.exec(part))){const status=m[3]; const topic=m[2].replace(/\s+/g,' ').trim(); rows.push({lesson:key,q:+m[1],topic,status,reason:status==='B'?'Boş bıraktım':(status==='Y'?'Belirtilmedi':'')});}}); return rows;}
function pick(s,r){const m=s.match(r); return m?m[1].trim():''} function num(x){return x?+String(x).replace(',','.'):0} function toISO(d){if(!d)return''; const m=d.match(/(\d{2})[-.](\d{2})[-.](\d{4})/); return m?`${m[3]}-${m[2]}-${m[1]}`:d}
function normalizeExam(e){e.id=e.id||uid(); e.lessons=e.lessons||{}; lessons.forEach(l=>{let x=e.lessons[l.key]||{}; x.total=+x.total||l.max; x.correct=clamp(+x.correct||0,0,x.total); x.wrong=clamp(+x.wrong||0,0,x.total-x.correct); x.blank=Math.max(0,x.total-x.correct-x.wrong); x.net=net(x.correct,x.wrong); e.lessons[l.key]=x;}); e.topics=e.topics||[]; return e;}
function clamp(n,a,b){return Math.min(Math.max(n,a),b)}
function fillReview(exam){$('reviewPanel').classList.remove('hidden'); const html=[]; html.push(`<div class="form-grid"><label>Sınav adı<input id="rvName" value="${esc(exam.name)}"></label><label>Tarih<input id="rvDate" type="date" value="${esc(exam.date)}"></label><label>TYT puan<input id="rvScore" type="number" step="0.001" value="${exam.score||''}"></label><label>Genel sıra<input id="rvRank" type="number" value="${exam.rank||''}"></label></div>`); html.push('<h4>Dersler</h4>'); lessons.forEach(l=>{const x=exam.lessons[l.key]; html.push(`<div class="topic-row"><b>${l.name}</b><span>Soru: ${x.total}</span><label>D <input class="rvCorrect" data-k="${l.key}" value="${x.correct}" type="number"></label><label>Y <input class="rvWrong" data-k="${l.key}" value="${x.wrong}" type="number"></label></div>`)}); const wrongs=exam.topics.filter(x=>x.status!=='D'); html.push(`<h4>Yanlış/Boş Konular (${wrongs.length})</h4>`); wrongs.slice(0,80).forEach((r,i)=>{html.push(`<div class="topic-row"><span>${lessonName(r.lesson)} ${r.q}. soru - <b>${esc(r.topic)}</b></span><span class="badge ${r.status==='Y'?'bad':''}">${r.status}</span><select class="rvReason" data-i="${i}">${reasons.map(x=>`<option ${x===r.reason?'selected':''}>${x}</option>`).join('')}</select></div>`)}); $('reviewForm').innerHTML=html.join('');}
function readReview(){const e=structuredClone(draft); e.name=$('rvName').value.trim(); e.date=$('rvDate').value; e.score=num($('rvScore').value); e.rank=num($('rvRank').value); document.querySelectorAll('.rvCorrect').forEach(inp=>{const k=inp.dataset.k; e.lessons[k].correct=+inp.value||0}); document.querySelectorAll('.rvWrong').forEach(inp=>{const k=inp.dataset.k; e.lessons[k].wrong=+inp.value||0}); const wrongRefs=e.topics.filter(x=>x.status!=='D'); document.querySelectorAll('.rvReason').forEach(sel=>{wrongRefs[+sel.dataset.i].reason=sel.value}); return normalizeExam(e);}
function saveExam(e){db.exams=db.exams.filter(x=>x.id!==e.id); db.exams.push(e); db.exams.sort((a,b)=>String(a.date).localeCompare(String(b.date))); if(e.historyFromFile?.length){e.historyFromFile.forEach(h=>{ if(!db.exams.some(x=>x.name===h.name&&x.date===h.date)){db.exams.push({id:uid(),name:h.name,date:h.date,score:h.score,rank:h.rank,lessons:{turkce:{total:40,correct:0,wrong:0,blank:40,net:0},sosyal:{total:25,correct:0,wrong:0,blank:25,net:0},matematik:{total:40,correct:0,wrong:0,blank:40,net:0},fen:{total:20,correct:0,wrong:0,blank:20,net:0}},manualTotalNet:h.net,topics:[]})}}); db.exams.sort((a,b)=>String(a.date).localeCompare(String(b.date))); } saveDB(); renderAll();}
function buildManual(){const wrap=$('lessonInputs'); lessons.forEach(l=>{const tpl=document.getElementById('lessonTemplate').content.cloneNode(true); const c=tpl.querySelector('.lesson-card'); c.dataset.k=l.key; c.querySelector('h3').textContent=l.name+` (${l.max} soru)`; c.querySelectorAll('input[type=range]').forEach(r=>r.max=l.max); c.querySelectorAll('input[type=number]').forEach(i=>i.max=l.max); wrap.appendChild(c);}); document.querySelectorAll('.lesson-card input').forEach(i=>i.addEventListener('input',syncManual)); $('saveManualBtn').onclick=()=>{const e=readManual(); saveExam(e); alert('Kaydedildi.');};}
function fillManual(e){draft=e; $('examName').value=e.name||'';$('examDate').value=e.date||today();$('examScore').value=e.score||'';$('examRank').value=e.rank||''; document.querySelectorAll('.lesson-card').forEach(c=>{const k=c.dataset.k,x=e.lessons[k]; c.querySelector('.correctInput').value=x.correct; c.querySelector('.correctRange').value=x.correct; c.querySelector('.wrongInput').value=x.wrong; c.querySelector('.wrongRange').value=x.wrong;}); renderTopicEditor(e); syncManual();}
function syncManual(e){document.querySelectorAll('.lesson-card').forEach(c=>{const max=lessons.find(l=>l.key===c.dataset.k).max; const ci=c.querySelector('.correctInput'), cr=c.querySelector('.correctRange'), wi=c.querySelector('.wrongInput'), wr=c.querySelector('.wrongRange'); const src=e?.target; if(src===cr)ci.value=cr.value; if(src===ci)cr.value=ci.value; if(src===wr)wi.value=wr.value; if(src===wi)wr.value=wi.value; let d=clamp(+ci.value||0,0,max), y=clamp(+wi.value||0,0,max-d); ci.value=cr.value=d; wi.value=wr.value=y; c.querySelector('.lesson-result').textContent=`Boş: ${max-d-y} | Net: ${net(d,y)}`;});}
function readManual(){const e=draft?structuredClone(draft):sampleExam(); e.id=e.id||uid(); e.name=$('examName').value||'Manuel Deneme'; e.date=$('examDate').value||today(); e.score=num($('examScore').value); e.rank=num($('examRank').value); document.querySelectorAll('.lesson-card').forEach(c=>{const k=c.dataset.k,max=lessons.find(l=>l.key===k).max,d=+c.querySelector('.correctInput').value||0,y=+c.querySelector('.wrongInput').value||0; e.lessons[k]={total:max,correct:d,wrong:y,blank:max-d-y,net:net(d,y)}}); document.querySelectorAll('.topicReason').forEach(sel=>{if(e.topics[+sel.dataset.i])e.topics[+sel.dataset.i].reason=sel.value}); return normalizeExam(e);}
function renderTopicEditor(e){const wrongs=e.topics.filter(x=>x.status!=='D'); $('topicEditor').innerHTML=wrongs.map((r,i)=>`<div class="topic-row"><span>${lessonName(r.lesson)} ${r.q}. soru - <b>${esc(r.topic)}</b></span><span class="badge ${r.status==='Y'?'bad':''}">${r.status}</span><select class="topicReason" data-i="${e.topics.indexOf(r)}">${reasons.map(x=>`<option ${x===r.reason?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')||'Konu verisi yok.';}
function initCompare(){$('compareBtn').onclick=renderCompare;}
function initBranch(){branchTypes.forEach(x=>$('branchType').insertAdjacentHTML('beforeend',`<option>${x}</option>`)); $('branchDate').value=today(); $('branchTotal').value=40; ['branchCorrect','branchWrong'].forEach(id=>$(id).value=0); document.querySelectorAll('.plus,.minus').forEach(b=>b.onclick=()=>{const inp=$(b.dataset.target); inp.value=Math.max(0,(+inp.value||0)+(b.classList.contains('plus')?1:-1)); syncBranch();}); ['branchCorrect','branchWrong','branchTotal'].forEach(id=>$(id).addEventListener('input',syncBranch)); $('saveBranchBtn').onclick=()=>{syncBranch(); const total=+$('branchTotal').value,d=+$('branchCorrect').value,y=+$('branchWrong').value; db.branches.push({id:uid(),type:$('branchType').value,name:$('branchName').value||$('branchType').value+' Denemesi',date:$('branchDate').value||today(),total,correct:d,wrong:y,blank:total-d-y,net:net(d,y)}); saveDB();renderAll();alert('Branş denemesi kaydedildi.')};}
function syncBranch(){const total=clamp(+$('branchTotal').value||1,1,80); let d=clamp(+$('branchCorrect').value||0,0,total); let y=clamp(+$('branchWrong').value||0,0,total-d); $('branchTotal').value=total;$('branchCorrect').value=d;$('branchWrong').value=y;$('branchBlank').value=total-d-y;}
function initHistory(){$('exportAllBtn').onclick=()=>downloadJSON(db,'tyt-analiz-yedek.json'); $('importAllBtn').onclick=async()=>{const f=$('importAllInput').files[0]; if(!f)return alert('JSON seç.'); db=JSON.parse(await f.text()); saveDB();renderAll();alert('Yedek yüklendi.')};}
function renderAll(){renderDashboard();renderTopics();renderSelectors();renderBranch();renderHistory();renderReport();}
function sortedExams(){return [...db.exams].sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function examNet(e){return +(e.manualTotalNet??sumNet(e))}
function renderDashboard(){const ex=sortedExams(),last=ex.at(-1),prev=ex.at(-2); $('examCount').textContent=ex.length; $('lastNet').textContent=last?examNet(last).toFixed(2):'—'; $('lastExamName').textContent=last?last.name:'Deneme yok'; $('deltaNet').textContent=last&&prev?fmt(examNet(last)-examNet(prev)):'—'; const agg=topicAgg(); $('criticalTopic').textContent=agg[0]?.topic||'—'; $('smartSummary').innerHTML=smartSummary(last,prev,agg); chart('netTimeline','line',ex.map(e=>e.name),[{label:'TYT Net',data:ex.map(examNet)}]); if(last) chart('lessonChart','bar',lessons.map(l=>l.name),[{label:last.name,data:lessons.map(l=>last.lessons[l.key]?.net||0)}]);}
function smartSummary(last,prev,agg){if(!last)return'Veri yükleyince otomatik yorum oluşacak.'; let s=`<b>${esc(last.name)}</b> toplam net: <b>${examNet(last).toFixed(2)}</b>. `; if(prev)s+=`Önceki denemeye göre <b>${fmt(examNet(last)-examNet(prev))}</b> net değişim var. `; if(agg[0])s+=`En öncelikli konu: <b>${esc(agg[0].topic)}</b>. Bu konu ${agg[0].count} kez yanlış/boş görülmüş.`; return s;}
function renderTopics(){const agg=topicAgg(); chart('topicRepeatChart','bar',agg.slice(0,12).map(x=>x.topic),[{label:'Yanlış/Boş tekrar',data:agg.slice(0,12).map(x=>x.count)}]); $('priorityList').innerHTML=agg.slice(0,10).map((x,i)=>`<div class="priority-row"><b>${i+1}. ${esc(x.topic)}</b><span>${lessonName(x.lesson)}</span><span class="badge bad">${x.count} tekrar</span><span class="badge">Öncelik ${x.priority}</span></div>`).join('')||'Konu verisi yok.'; $('topicTable').innerHTML=agg.map(x=>`<div class="topic-row"><span><b>${esc(x.topic)}</b><br><small>${lessonName(x.lesson)} | Neden: ${esc(x.reasons.join(', ')||'Belirtilmedi')}</small></span><span class="badge bad">Y/B: ${x.count}</span><span class="badge">Son: ${esc(x.lastDate)}</span><span class="badge">${x.priority}</span></div>`).join('')||'Konu verisi yok.';}
function topicAgg(){const map={}; sortedExams().forEach(e=>e.topics?.filter(t=>t.status!=='D').forEach(t=>{const k=t.lesson+'|'+t.topic; if(!map[k])map[k]={lesson:t.lesson,topic:t.topic,count:0,reasons:[],lastDate:e.date,priority:0}; map[k].count++; if(t.reason&&!map[k].reasons.includes(t.reason))map[k].reasons.push(t.reason); map[k].lastDate=e.date;})); return Object.values(map).map(x=>{x.priority=x.count*20+(new Date(x.lastDate)>new Date(Date.now()-1000*60*60*24*21)?15:0); return x}).sort((a,b)=>b.priority-a.priority)}
function renderSelectors(){const ex=sortedExams(); ['compareA','compareB'].forEach(id=>{$(id).innerHTML=ex.map(e=>`<option value="${e.id}">${e.date} - ${esc(e.name)} (${examNet(e).toFixed(2)})</option>`).join('')}); if(ex.length>1){$('compareA').value=ex[0].id;$('compareB').value=ex.at(-1).id}}
function renderCompare(){const a=db.exams.find(e=>e.id===$('compareA').value),b=db.exams.find(e=>e.id===$('compareB').value); if(!a||!b)return; const rows=lessons.map(l=>{const d=(b.lessons[l.key]?.net||0)-(a.lessons[l.key]?.net||0); return `<div class="compare-row"><b>${l.name}</b><span>${(a.lessons[l.key]?.net||0).toFixed(2)} → ${(b.lessons[l.key]?.net||0).toFixed(2)}</span><span class="badge ${d<0?'bad':'good'}">${fmt(d)}</span><span>${d<0?'Düşüş':'Artış'}</span></div>`}).join(''); $('compareResult').classList.remove('hidden'); $('compareResult').innerHTML=`<h3>${esc(a.name)} vs ${esc(b.name)}</h3><div class="compare-row"><b>Toplam Net</b><span>${examNet(a).toFixed(2)} → ${examNet(b).toFixed(2)}</span><span class="badge ${(examNet(b)-examNet(a))<0?'bad':'good'}">${fmt(examNet(b)-examNet(a))}</span><span></span></div>${rows}`;}
function renderBranch(){const br=[...db.branches].sort((a,b)=>String(a.date).localeCompare(String(b.date))); chart('branchChart','line',br.map(x=>x.name),[{label:'Branş net',data:br.map(x=>x.net)}]); $('branchHistory').innerHTML=br.map(x=>`<div class="history-row"><b>${esc(x.name)}</b><span>${x.type}</span><span>${x.date}</span><span class="badge">${x.net}</span></div>`).join('')||'Branş denemesi yok.';}
function renderHistory(){const ex=sortedExams(); $('historyList').innerHTML=ex.map(e=>`<div class="history-row"><b>${esc(e.name)}</b><span>${e.date}</span><span class="badge">${examNet(e).toFixed(2)} net</span><span><button class="ghost" onclick="downloadExam('${e.id}')">İndir</button> <button class="ghost" onclick="editExam('${e.id}')">Düzelt</button> <button class="ghost" onclick="deleteExam('${e.id}')">Sil</button></span></div>`).join('')||'Henüz kayıt yok.';}
function renderReport(){const ex=sortedExams(),last=ex.at(-1),prev=ex.at(-2),agg=topicAgg(); $('reportSummary').innerHTML=last?`<p><b>Son deneme:</b> ${esc(last.name)} | <b>Tarih:</b> ${last.date} | <b>Net:</b> ${examNet(last).toFixed(2)} ${prev?`| <b>Fark:</b> ${fmt(examNet(last)-examNet(prev))}`:''}</p><div>${lessons.map(l=>`<span class="badge">${l.name}: ${(last.lessons[l.key]?.net||0).toFixed(2)}</span> `).join('')}</div>`:'Veri yok.'; chart('reportNetChart','line',ex.map(e=>e.name),[{label:'TYT Net',data:ex.map(examNet)}]); $('reportTopics').innerHTML=agg.slice(0,12).map(x=>`<div class="priority-row"><b>${esc(x.topic)}</b><span>${lessonName(x.lesson)}</span><span>${x.count} tekrar</span><span>Öncelik ${x.priority}</span></div>`).join('')||'Konu verisi yok.'; $('reportPlan').innerHTML=agg.slice(0,5).map((x,i)=>`<p><b>Gün ${i+1}:</b> ${esc(x.topic)} çalış + 25 soru çöz + yanlış defterine ekle.</p>`).join('')||'Öncelik listesi için konu verisi gerekli.';}
function chart(id,type,labels,datasets){const el=$(id); if(!el||typeof Chart==='undefined')return; if(charts[id])charts[id].destroy(); charts[id]=new Chart(el,{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#dbeafe'}}},scales:{x:{ticks:{color:'#9fb0d0'},grid:{color:'rgba(255,255,255,.08)'}},y:{ticks:{color:'#9fb0d0'},grid:{color:'rgba(255,255,255,.08)'}}}}});}
function fmt(n){n=+n; return (n>=0?'+':'')+n.toFixed(2)} function lessonName(k){return lessons.find(l=>l.key===k)?.name||k}
window.downloadExam=id=>{const e=db.exams.find(x=>x.id===id); if(e)downloadJSON({exam:e},`analiz-${e.date}-${safe(e.name)}.json`)}; window.editExam=id=>{const e=db.exams.find(x=>x.id===id); if(e){fillManual(structuredClone(e));showPage('manual')}}; window.deleteExam=id=>{if(confirm('Silinsin mi?')){db.exams=db.exams.filter(e=>e.id!==id);saveDB();renderAll();}};
function downloadJSON(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); URL.revokeObjectURL(a.href)} function safe(s){return String(s).replace(/[^a-z0-9çğıöşü_-]+/gi,'-').slice(0,40)}
function sampleExam(){return normalizeExam({id:uid(),name:'O POZİTİF TYT+AYT',date:'2026-05-04',score:285.557,rank:327,lessons:{turkce:{total:40,correct:26,wrong:11,blank:3},sosyal:{total:25,correct:14,wrong:5,blank:6},matematik:{total:40,correct:11,wrong:2,blank:27},fen:{total:20,correct:13,wrong:6,blank:1}},topics:[{lesson:'turkce',q:8,topic:'PARAGRAF',status:'Y',reason:'Belirtilmedi'},{lesson:'turkce',q:9,topic:'NOKTALAMA',status:'Y',reason:'Belirtilmedi'},{lesson:'turkce',q:10,topic:'YAZIM KURALLARI',status:'Y',reason:'Belirtilmedi'},{lesson:'matematik',q:3,topic:'KÖKLÜ SAYI',status:'Y',reason:'Belirtilmedi'},{lesson:'matematik',q:14,topic:'ORAN ORANTI',status:'Y',reason:'Belirtilmedi'},{lesson:'fen',q:1,topic:'FİZİK BİLİMİ',status:'Y',reason:'Belirtilmedi'},{lesson:'fen',q:2,topic:'ISI SICAKLIK',status:'Y',reason:'Belirtilmedi'},{lesson:'fen',q:18,topic:'HÜCRE BÖLÜNMESİ',status:'Y',reason:'Belirtilmedi'}]});}
// İlk açılışta manuel tarih boş kalmasın
setTimeout(()=>{if($('examDate'))$('examDate').value=today();},100);
